export class BancosBr{
  public static bancosBrasil = [
    "Banco do Brasil S.A.",
    "Caixa Econômica Federal",
    "Banco Bradesco S.A.",
    "Banco Itaú Unibanco S.A.",
    "Banco Santander (Brasil) S.A.",
    "Banco Safra S.A.",
    "Banco BTG Pactual S.A.",
    "Banco Original S.A.",
    "Banco Pine S.A.",
    "Banco C6 S.A.",
    "Banco Pan S.A.",
    "Banco Inter S.A.",
    "Nubank S.A.",
    "Banco Modal S.A.",
    "Banco BS2 S.A.",
    "Banco Neon S.A.",
    "Banco Renner",
    "Banco Crefisa S.A.",
    "Banco Agibank S.A.",
    "Banco BMG S.A.",
    "Banco Daycoval S.A.",
    "Banco ABC Brasil S.A.",
    "Banco Sofisa S.A.",
    "Banco Alvorada S.A.",
    "Banco Intermedium",
    "Banco Fibra S.A.",
    "Banco Topázio S.A.",
    "Banco Maxinvest",
    "Banco J. Safra S.A.",
    "Banco Votorantim S.A.",
    "Banco Alfa S.A.",
    "Banco Mercantil do Brasil S.A.",
    "Banco Ourinvest S.A.",
    "Banco Cooperativo Sicredi S.A.",
    "Banco da Amazônia S.A.",
    "Banco do Estado do Rio Grande do Sul S.A.",
    "Banco da China Brasil S.A.",
    "Banco de Brasília S.A.",
    "Banco de Desenvolvimento de Minas Gerais S.A.",
    "Banco de Desenvolvimento do Espírito Santo S.A.",
    "Banco de Desenvolvimento do Estado de São Paulo S.A.",
    "Banco de Investimento Credit Suisse (Brasil) S.A.",
    "Banco de Investimento Imobiliário",
    "Banco de Investimentos",
    "Banco Interamericano de Desenvolvimento",
    "Banco Triângulo S.A.",
    "Banco Tripartite S.A.",
    "Banco de Lage Landen Brasil S.A.",
    "Banco do Estado de Sergipe S.A.",
  ];
  }
